src/Entity/Sortie.php
<?php

namespace App\Entity;

use App\Repository\SortieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=SortieRepository::class)
 */
class Sortie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank(message="Nom de la sortie manquant")
     * @Assert\Length(max="100",maxMessage="Ce nom est trop long (100 charactères maximum)")
     * @ORM\Column(type="string", length=100)
     */
    private $nom;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan("now", message="La date de la sortie ne peut pas être révolue.")
     */
    private $date_heure_debut;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\GreaterThan(value=0, message="La durée doit être supérieure à 0")
     */
    private $duree;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\LessThan(propertyPath="date_heure_debut", message="La date de fin des inscriptions ne peut pas être
     * avant la date de début de la sortie.")
     * @Assert\GreaterThan("now", message="La date de fin des inscriptions ne peut pas être révolue.")
     */
    private $date_limite_inscription;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThan(value=0, message="La nombre de participant doit être supérieur à 0")
     */
    private $nb_inscriptions_max;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Participant::class, inversedBy="sortie_organisee")
     * @ORM\JoinColumn(nullable=false)
     */
    private $organisateur;

    /**
     * @ORM\ManyToMany(targetEntity=Participant::class, mappedBy="sortie_participee")
     */
    private $participants;

    /**
     * @ORM\ManyToOne(targetEntity=Campus::class, inversedBy="sorties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $campus;

    /**
     * @ORM\ManyToOne(targetEntity=Lieu::class, inversedBy="sorties", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $lieu;

    /**
     * @ORM\ManyToOne(targetEntity=Etat::class, inversedBy="sorties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $etat;



    public function __construct()
    {
        $this->participants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateHeureDebut(): ?\DateTimeInterface
    {
        return $this->date_heure_debut;
    }

    public function setDateHeureDebut(\DateTimeInterface $date_heure_debut): self
    {
        $this->date_heure_debut = $date_heure_debut;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(?int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getDateLimiteInscription(): ?\DateTimeInterface
    {
        return $this->date_limite_inscription;
    }

    public function setDateLimiteInscription(\DateTimeInterface $date_limite_inscription): self
    {
        $this->date_limite_inscription = $date_limite_inscription;

        return $this;
    }

    public function getNbInscriptionsMax(): ?int
    {
        return $this->nb_inscriptions_max;
    }

    public function setNbInscriptionsMax(int $nb_inscriptions_max): self
    {
        $this->nb_inscriptions_max = $nb_inscriptions_max;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getOrganisateur(): ?Participant
    {
        return $this->organisateur;
    }

    public function setOrganisateur(?Participant $organisateur): self
    {
        $this->organisateur = $organisateur;
        return $this;
    }

    /**
     * @return Collection|Participant[]
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Participant $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
            $participant->addSortieParticipee($this);
        }

        return $this;
    }

    public function removeParticipant(Participant $participant): self
    {
        if ($this->participants->contains($participant)) {
            $this->participants->removeElement($participant);
            $participant->removeSortieParticipee($this);
        }

        return $this;
    }

    public function getCampus(): ?Campus
    {
        return $this->campus;
    }

    public function setCampus(?Campus $campus): self
    {
        $this->campus = $campus;

        return $this;
    }

    public function getLieu(): ?Lieu
    {
        return $this->lieu;
    }

    public function setLieu(?Lieu $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getEtat(): ?Etat
    {
        return $this->etat;
    }

    public function setEtat(?Etat $etat): self
    {
        $this->etat = $etat;

        return $this;
    }


}

src/Entity/Ville.php
<?php

namespace App\Entity;

use App\Repository\VilleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VilleRepository::class)
 */
class Ville
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $code_postal;

    /**
     * @ORM\OneToMany(targetEntity=Lieu::class, mappedBy="ville", orphanRemoval=true)
     * @Assert\NotBlank()
     */
    private $lieux;

    public function __construct()
    {
        $this->lieux = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->nom;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    /**
     * @return Collection|Lieu[]
     */
    public function getLieux(): Collection
    {
        return $this->lieux;
    }

    public function addLieu(Lieu $lieu): self
    {
        if (!$this->lieux->contains($lieu)) {
            $this->lieux[] = $lieu;
            $lieu->setVille($this);
        }

        return $this;
    }

    public function removeLieu(Lieu $lieu): self
    {
        if ($this->lieux->contains($lieu)) {
            $this->lieux->removeElement($lieu);
            // set the owning side to null (unless already changed)
            if ($lieu->getVille() === $this) {
                $lieu->setVille(null);
            }
        }

        return $this;
    }
}

src/Controller/SortieController.php
<?php

namespace App\Controller;

use App\Entity\Etat;
use App\Entity\Lieu;
use App\Entity\Participant;
use App\Entity\Sortie;
use App\Form\SortieCancelType;
use App\Form\SortieType;
use App\Repository\SortieRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/sortie")
 */
class SortieController extends AbstractController
{
    /**
     * @Route("/", name="sortie_index", methods={"GET"})
     * @param SortieRepository $sortieRepository
     * @return Response
     */
    public function index(SortieRepository $sortieRepository): Response
    {
        return $this->render('sortie/index.html.twig', [
            'sorties' => $sortieRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="sortie_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $sortie = new Sortie();
        $form = $this->createForm(SortieType::class, $sortie);
        $form->handleRequest($request);

        $organisateur = $this->getUser();
        $organisateur->addSortieOrganisee($sortie);

        if ($form->isSubmitted() && $form->isValid()) {
            $new = true;
            $this->actions($request, $sortie, $new);
            return $this->redirectToRoute('default_accueil');
        }

        return $this->render('sortie/new.html.twig', [
            'sortie' => $sortie,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="sortie_show", methods={"GET"}, requirements={"id": "\d+"})
     * @param Sortie $sortie
     * @return Response
     */
    public function show(Sortie $sortie): Response
    {
        return $this->render('sortie/show.html.twig', [
            'sortie' => $sortie,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="sortie_edit", methods={"GET","POST"}, requirements={"id": "\d+"})
     * @param Request $request
     * @param Sortie $sortie
     * @return Response
     */
    public function edit(Request $request, Sortie $sortie): Response
    {
        $userco = $this->getUser();
        if($userco != $sortie->getOrganisateur()){
            $this->addFlash('warning','Vous ne pouvez pas modifier cette sortie car vous n\'etes pas l\'organisateur.');
            return $this->redirectToRoute('default_accueil');
        }
        elseif(1 != $sortie->getEtat()->getId()){ //check si l'état de la sortie vaut 1 =>  etat créée
            $this->addFlash('warning','Vous ne pouvez pas modifier une sortie déjà publiée.');
            return $this->redirectToRoute('default_accueil');
        }
        $form = $this->createForm(SortieType::class, $sortie);
        $form->handleRequest($request);
        $new = false;

        if ($form->isSubmitted() && $form->isValid()) {
            $this->actions($request, $sortie, $new);
            return $this->redirectToRoute('default_accueil');
        }

        return $this->render('sortie/edit.html.twig', [
            'sortie' => $sortie,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="sortie_delete", methods={"DELETE"}, requirements={"id": "\d+"})
     * @param Request $request
     * @param Sortie $sortie
     * @return Response
     */
    public function delete(Request $request, Sortie $sortie): Response
    {
        if ($this->isCsrfTokenValid('delete'.$sortie->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($sortie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('sortie_index');
    }

    /**
     * @Route("/{id}/publish", name="sortie_publish", requirements={"id": "\d+"})
     * @param Sortie $sortie
     * @param EntityManagerInterface $em
     * @return RedirectResponse
     */
    public function publish(Sortie $sortie, EntityManagerInterface $em){
        $etat = $this->getDoctrine()->getManager()->getRepository('App:Etat')->find(2);
        $sortie->setEtat($etat);
        $em->flush();
        $this->addFlash('success','La sortie a été publiée !');
        return $this->redirectToRoute('default_accueil');
    }

    /**
     * @Route("/{id}/register", name="sortie_registration", requirements={"id": "\d+"})
     * @param Sortie $sortie
     * @param EntityManagerInterface $em
     * @return RedirectResponse
     */
    public function registration(Sortie $sortie, EntityManagerInterface $em)
    {
        $userco = $this->getUser();
        $em = $this->getDoctrine()->getManager();
        $etatRepo = $em->getRepository(Etat::class);
        $etatCloture = $etatRepo->find(3);
        $dateActuelle =  new DateTime();

        //Conditions pour pouvoir s\inscrire a une sortie

        // ID 2 = etat ouvert
        if ($sortie->getEtat()->getId() !=2)
        {
            $this->addFlash('warning', 'L\'état de la sortie ne permet pas de vous inscrire');

        }
        elseif ($sortie->getNbInscriptionsMax() == $sortie->getParticipants()->count())
        {
            $this->addFlash('warning', 'Le nombre maximum de participant à été atteint');

        }
        elseif ($sortie->getParticipants()->contains($userco))
        {
               $this->addFlash('warning','Vous êtes déjà inscrit à la sortie');

        }
        elseif ($sortie->getDateLimiteInscription() < $dateActuelle)
        {
            $this->addFlash('warning', 'La période d\'inscription pour cette sortie est terminée' );
        }
        else
        {
            $sortie->addParticipant($userco);
            $this->addFlash('success', 'Vous avez bien été inscrit à la sortie');
            if($sortie->getNbInscriptionsMax() == $sortie->getParticipants()->count()){
                $sortie->setEtat($etatCloture);
            }
        }
        //Enregistrement des données (update)
        $em->flush();

        return $this->redirectToRoute('default_accueil');
    }

    /**
     * @Route("/{id}/unregister", name="sortie_unregistration", requirements={"id": "\d+"})
     * @param Sortie $sortie
     * @param EntityManagerInterface $em
     * @return RedirectResponse
     */
    public function unregistration(Sortie $sortie, EntityManagerInterface $em)
    {
        $userco = $this->getUser();
        $etatRepo = $em->getRepository(Etat::class);
        $etatOuvert = $etatRepo->find(2);
        $etatCloture = $etatRepo->find(3);
        $etatEnCours = $etatRepo->find(4);
        $dateActuelle =  new DateTime();

        if($sortie->getDateLimiteInscription() > $dateActuelle ){
            $sortie->setEtat($etatOuvert);
        }elseif ($sortie->getDateHeureDebut() < $dateActuelle ){
            $sortie->setEtat($etatCloture);
        }else{
            $sortie->setEtat($etatEnCours);
        }

        if($sortie->getEtat() != $etatEnCours){
            $sortie->removeParticipant($userco);
            $this->addFlash('success', 'Vous vous êtes bien désinscrit de la sortie');
        }else{
            $this->addFlash('warning', 'Il est trop tard pour vous désinscrire de cette sortie');
        }

        $em->flush();
        return $this->redirectToRoute('default_accueil');
    }

    /**
     * @Route("/{id}/cancel", name="sortie_cancel", requirements={"id": "\d+"})
     * @param Sortie $sortie
     * @param EntityManagerInterface $em
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function cancel(Sortie $sortie, EntityManagerInterface $em, Request $request)
    {
        $userco = $this->getUser();

        if($userco != $sortie->getOrganisateur() or ($sortie->getEtat()->getId() != 2 && $sortie->getEtat()->getId() != 3) ){
            $this->addFlash('warning','Vous ne pouvez pas annuler cette sortie !');
            return $this->redirectToRoute('default_accueil');
        }

        $originalDescription = $sortie->getdescription();
        $sortie->setDescription('');
        $form = $this->createForm(SortieCancelType::class, $sortie);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
            {
                $sortie->setDescription('MOTIF D\'ANNULATION : ' . $sortie->getDescription() . '; DESCRIPTION ORIGINALE : ' . $originalDescription);
                $etat = $this->getDoctrine()->getManager()->getRepository(Etat::class)->find(6);
                $sortie->setEtat($etat);
                $em->flush();
                $this->addFlash('success', 'Sortie annulée !');
                return $this->redirectToRoute('default_accueil') ;
            }
        return $this->render('sortie/cancel.html.twig',
            ['sortie' => $sortie,
            'form' => $form->createView()]);

    }

    /**
     * Returns a JSON string with the neighborhoods of the City with the providen id.
     * @Route("/lieux", name="sortie_lieux")
     * @param Request $request
     * @return JsonResponse
     */
    public function lieuxVille(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $lieuRepo = $em->getRepository(Lieu::class);

        $lieux = $lieuRepo->createQueryBuilder("q")
            ->where("q.ville = :villeid")
            ->setParameter("villeid", $request->query->get("villeid"))
            ->getQuery()
            ->getResult();
        $responseArray = array();

        foreach($lieux as $lieu){
            $responseArray[] = array(
                "id" => $lieu->getId(),
                "nom" => $lieu->getNom()
            );
        }

        return new JsonResponse($responseArray);

    }

templates/sortie/_delete_form.html.twig
<form method="post" action="{{ path('sortie_delete', {'id': sortie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sortie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/sortie/cancel.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }}Annuler une sortie{% endblock %}

{% block body %}

    <div class="d-none d-md-block">
        <h1>Annuler la Sortie</h1>
        <div class="row d-flex justify-content-center mt-5">
            <div class="col-lg-2 col-md-4 mr-lg-0"  >
                <p class="font-weight-bold text-nowrap">Nom de la sortie :</p>
                <p class="font-weight-bold text-nowrap">Date et heure de la sortie : </p>
                <p class="font-weight-bold text-nowrap">Campus : </p>
                <p class="font-weight-bold">Lieu : </p>
            </div>
            <div class="col-lg-2 col-md-3" >
                <p> {{ sortie.nom }}</p>
                <p> {{ sortie.dateHeureDebut|date('d-m-Y H:i:s') }}</p>
                <p>{{ sortie.campus.nom }}</p>
                <p> {{ sortie.lieu.nom }}</p>
                <p> {{ sortie.description }}</p>
            </div>

        </div>
        <div class="d-flex justify-content-center">
            <div class="text-center col-lg-5 ">
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <a class="btn btn-secondary" href="{{ path('default_accueil') }}">Retour</a>
                <input type="submit" class="btn btn-primary" name="submit" value="Confirmer l'annulation">
                {{ form_end(form) }}
            </div>
        </div>

    </div>

{% endblock %}

templates/sortie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }}Modifier une sortie{% endblock %}

{% block body %}
    <div class="d-none d-md-block">
        <h1>Modifier une sortie</h1>
        <div class="row d-flex justify-content-center">
            <div class="col-md-5 col-lg-4 mt-5">
                {{ form_start(form) }}
                {{ form_row(form.nom) }}
                {{ form_row(form.date_heure_debut) }}
                {{ form_row(form.date_limite_inscription) }}
                {{ form_row(form.duree) }}
                {{ form_row(form.nb_inscriptions_max) }}
            </div>
            <div class="col-md-5 col-lg-4 mt-5">
                {{ form_row(form.description) }}
                {{ form_row(form.campus) }}
                {{ form_row(form.ville) }}
                {{ form_row(form.lieu) }}
                <div class="text-center mt-5">
                    <a class="btn btn-secondary" href="{{ path('default_accueil') }}">Annuler les modifications</a>
                    <input type="submit" class="btn btn-primary" name="submit" value="Enregistrer"></input>
                    <input type="submit" class="btn btn-success" name="submit" value="Publier"></input>
                    <input type="submit" class="btn btn-danger" name="submit" value="Supprimer la sortie"></input>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/app.js') }}"></script>
{% endblock %}

templates/sortie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sortie index{% endblock %}

{% block body %}


    <h1>Sortie index</h1>
    <div class="container" >

        <table class="table table-striped">
        <thead>
        <tr>

            <th>Nom de la sortie</th>
            <th>Date de la sortie</th>
            <th>Clôture</th>
            <th>inscrits/places</th>
            <th>Etat</th>
            <th>Inscrit</th>
            <th>Organisateur</th>
            <th>actions</th>
        </tr>
        </thead>


        <tbody>
        {% for sortie in sorties %}
            <tr>

                <td colspan="1">{{ sortie.nom }}</td>
                <td colspan="1">{{ sortie.dateHeureDebut ? sortie.dateHeureDebut|date('Y-m-d H:i:s') : '' }}</td>
                <td colspan="1">{{ sortie.dateLimiteInscription ? sortie.dateLimiteInscription|date('Y-m-d ') }}</td>
                <td colspan="1"> ? / {{ sortie.nbInscriptionsMax }}</td>
                <td colspan="1"> {{ sortie.etat.libelle }}</td>
                <td colspan="1"> </td>
                <td colspan="1"> {{ sortie.organisateur.prenom }}.{{ sortie.organisateur.nom }}</td>
                <td colspan="1">
                    <a href="{{ path('sortie_show', {'id': sortie.id}) }}">Afficher</a>
                    <a href="{{ path('sortie_edit', {'id': sortie.id}) }}">Modifier</a>
                    <a href="{{ path('sortie_show', {'id': sortie.id}) }}">Publier</a>
                    <a href="{{ path('sortie_show', {'id': sortie.id}) }}">Se désister</a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
    <div class="btn">
    <button class="primary" ><a href="{{ path('sortie_new') }}">Créer une sortie</a> </button>
    </div>
{% endblock %}

templates/sortie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }}Sortie{% endblock %}

{% block body %}
    {%  set inscrit = false %}
    <h1>Sortie</h1>
    <div class="d-none d-md-block">
        <div class="row mt-2 d-flex justify-content-center">
            <div class="col-md-5"  >
                <p><span class="font-weight-bold text-nowrap">Nom de la sortie : </span>{{ sortie.nom }}</p>
                <p><span class="font-weight-bold text-nowrap">Date et heure de la sortie : </span>{{ sortie.dateHeureDebut|date('d-m-Y H:i:s') }}</p>
                <p><span class="font-weight-bold text-nowrap">Date limite d'inscription : </span>{{ sortie.dateLimiteInscription ? sortie.dateLimiteInscription|date('d-m-Y ') }}</p>
                <p><span class="font-weight-bold text-nowrap">Nombre de places : </span>{{ sortie.nbInscriptionsMax }}</p>
                <p><span class="font-weight-bold text-nowrap">Durée : </span>{{ sortie.duree }} minutes</p>
                <p><span class="font-weight-bold text-nowrap">Description et infos : </span>{{ sortie.description }}</p>
            </div>
            <div class="col-md-5">
                <p><span class="font-weight-bold text-nowrap">Campus : </span>{{ sortie.campus.nom }}</p>
                <p><span class="font-weight-bold text-nowrap">Lieu :  </span>{{ sortie.lieu.nom }}</p>
                <p><span class="font-weight-bold text-nowrap">Rue : </span>{{ sortie.lieu.rue }}</p>
                <p><span class="font-weight-bold text-nowrap">Code postal : </span>{{ sortie.lieu.ville.codePostal }}</p>
                <p><span class="font-weight-bold text-nowrap">Ville : </span>{{ sortie.lieu.ville.nom }}</p>
                <p><span class="font-weight-bold text-nowrap">Latitude : </span>
                    {% if sortie.lieu.latitude | length == 0 %}
                        {{  " Aucune info"      }}
                    {% endif %}
                    {{ sortie.lieu.latitude }}</p>
                <p><span class="font-weight-bold text-nowrap">Longitude : </span>
                    {% if sortie.lieu.longitude | length == 0 %}
                        {{  " Aucune info"      }}
                    {% endif %}
                    {{ sortie.lieu.longitude}} </p>
            </div>
        </div>
    </div>
    {#Code pour mobile#}
    <div class="d-block d-md-none">
        <div class="row mt-3">
            <div class="col-12"  >
                <p><span class="font-weight-bold text-nowrap">Nom : </span>{{ sortie.nom }}</p>
                <p><span class="font-weight-bold text-nowrap">Date et heure : </span>{{ sortie.dateHeureDebut|date('d-m-Y H:i:s') }}</p>
                <p><span class="font-weight-bold text-nowrap">Ville: </span>{{ sortie.lieu.ville.nom }}</p>
                <p><span class="font-weight-bold text-nowrap">Lieu : </span>{{ sortie.lieu.nom }}</p>
                <p><span class="font-weight-bold text-nowrap">Rue : </span>{{ sortie.lieu.rue }}</p>
                <p><span class="font-weight-bold text-nowrap">Code postal : </span>{{ sortie.lieu.ville.codePostal }}</p>
                <p><span class="font-weight-bold text-nowrap">Latitude : </span>
                    {% if sortie.lieu.latitude | length == 0 %}
                        {{  " Aucune info"      }}
                    {% endif %}
                    {{ sortie.lieu.latitude }}</p>
                <p><span class="font-weight-bold text-nowrap">Longitude : </span>
                    {% if sortie.lieu.longitude | length == 0 %}
                        {{  " Aucune info"      }}
                    {% endif %}
                    {{ sortie.lieu.longitude}}</p>
                <p><span class="font-weight-bold text-nowrap">Clôture : </span>{{ sortie.dateLimiteInscription ? sortie.dateLimiteInscription|date('d-m-Y ') }}</p>
                <p><span class="font-weight-bold text-nowrap">Nombre de places : </span>{{ sortie.nbInscriptionsMax }}</p>
                <p><span class="font-weight-bold text-nowrap">Durée : </span>{{ sortie.duree }} minutes</p>
                <p><span class="font-weight-bold text-nowrap">Description et infos : </span>{{ sortie.description }}</p>
            </div>
        </div>
    </div>
    <br/>
    <div class="col-lg-4" >
    {% if sortie.participants | length > 0 %}

        <h4>Liste des participants</h4>
        <table class="table table-striped ">

            <thead>
                <tr>
                    <th class="d-none d-md-block">Pseudo</th>
                    <th>Nom</th>
                </tr>
            </thead>
            <tbody>
                {% for participant in sortie.participants %}
                    {% if app.user.id == participant.id %}
                        {% set inscrit = true %}
                    {% endif %}
                <tr>
                    <td class="d-none d-md-block"><a href="{{ path('participant_show',{'id': participant.id}) }}"> {{ participant.pseudo }}</a></td>
                    <td > {{ participant.prenom }} {{ participant.nom }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h4>Aucun participant pour cette sortie</h4>
    {% endif%}
    </div>
    <div class="d-none d-md-block col-lg-4 mx-auto text-center">
        <a class="btn btn-secondary" href="{{ path('default_accueil') }}">Retour</a>
        {% if app.user.id == sortie.organisateur.id %}
            {% if sortie.etat.id == 2 %}
                <a class="btn btn-primary" href="{{ path('sortie_edit', {'id': sortie.id}) }}">Modifier la sortie</a>
                <a class="btn btn-primary" href="{{ path('sortie_cancel', {'id': sortie.id}) }}">Annuler la sortie</a>
            {% endif %}
        {% elseif inscrit %}
            <a class="btn btn-primary" href="{{ path('sortie_unregistration', {'id': sortie.id})  }}">Se désister</a>
        {% else %}
            <a class="btn btn-primary" href="{{ path('sortie_registration', {'id': sortie.id})  }}">S'inscrire</a>
        {% endif %}
    </div>
{% endblock %}